### PR TITLE
Fix docs URL

### LINKED ISSUE #113: Docs page has invalid SSL certificate
https://certifi.kennethreitz.org/en/latest/

### LINKED ISSUE #118: certifi.io redirects to https://pip.pypa.io/en/stable/
```
$ curl -v http://certifi.io
*   Trying 51.158.74.197:80...
* TCP_NODELAY set
* Connected to certifi.io (51.158.74.197) port 80 (#0)
> GET / HTTP/1.1
> Host: certifi.io
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
< Server: nginx/1.10.3 (Ubuntu)
< Date: Mon, 24 Feb 2020 14:30:37 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 0
< Connection: keep-alive
< Location: http://pip.pypa.io/en/stable/
< X-RTD-System-Redirect: True
< X-Frame-Options: DENY
< x-content-type-options: nosniff
< x-xss-protection: 1; mode=block
< X-Served: Django-Proxito
< X-Deity: web04
< Strict-Transport-Security: max-age=0
< 
* Connection #0 to host certifi.io left intact
```
(and same result in https)

### PR DESCRIPTION
**Pull request by divbzero**
Resolves #113.
Resolves #118.

Related to and closes #85.

### CODE REVIEW

**Comment by divbzero** [comment]
The project URLs added in 3f94c76 mimic [`setup.py#L109-L112`][1] for Requests and also follow @hugovk’s requested changes for #85.

[1]: https://github.com/psf/requests/blob/2758124a13cddff7244b97b5ffe3fddabb90bc18/setup.py#L109-L112

**Comment by Lukasa** [comment]
Thanks!

**Comment by divbzero** [comment]
Thank you!

**Comment by mstathers** [comment]
```
  File "setup.py", line 68
    project_urls: {
                ^
SyntaxError: invalid syntax
```


Since this pull request was merged.

**Comment by hugovk** [comment]
Please see PR https://github.com/certifi/python-certifi/pull/121 to fix this.

**Comment by h1z1** [comment]
This is  broken again(?)

https://certifiio.readthedocs.io/en/latest/ redirects to certifi.io which throws up a 403 error from Cloudflare

Why on Earth such a critical package would have links like that is something I can only speculate.

**Comment by hugovk** [comment]
@h1z1 Tracked in https://github.com/certifi/python-certifi/issues/132.

**Pull request merged**
