### PR TITLE
Use HTTPS for certifi.io

### PR DESCRIPTION
**Pull request by adamchainz**
Use the securities.

### CODE REVIEW

**Comment by adamchainz** [comment]
The GitHub description field should be changed too:

screen shot 2018-10-29 at 10 29 15

**Comment by adamchainz** [comment]
Thanks

The github description still needs editing as per the above screenshot

**Comment by sigmavirus24** [comment]
I don't have the permissions to do that.

**Comment by adamchainz** [comment]
Fair

**Pull request merged**
