### PR TITLE
Stop linking to broken certifi.io

### PR DESCRIPTION
**Pull request by adamchainz**

### CODE REVIEW

**Comment by adamchainz** [comment]
This also needs updating on the GitHub description field:

screen shot 2018-10-29 at 10 29 15

**Comment by adamchainz** [comment]
It might come back from https://github.com/certifi/certifi.io/issues/19

**Comment by adamchainz** [comment]
It's back

**Comment by benoitc** [comment]
Instance was archived by error last Sunday. Next time please open a ticket first :)

**Pull request closed without merging**
